[package]
name = "waterbase"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.76"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[features]
async = []

[lib]
name = "waterbase"
path = "src/lib.rs"
crate-type = ["rlib"]
