on: [push, pull_request]

name: Rust Lib

jobs:
  check_lib:
    name: Check Lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: libaries/rust  # Specify the path to your Rust project

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        working-directory: libaries/rust  # Specify the path to your Rust project
        run: cargo check

  test_lib:
    name: Test Suite Lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: libaries/rust  # Specify the path to your Rust project

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        working-directory: libaries/rust  # Specify the path to your Rust project
        run: cargo test

  lints_lib:
    name: Lints Lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: libaries/rust  # Specify the path to your Rust project

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        working-directory: libaries/rust  # Specify the path to your Rust project
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        working-directory: libaries/rust  # Specify the path to your Rust project
        run: cargo clippy -- -D warnings

  check_tests:
    name: Check Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: libaries/tests/rust  # Specify the path to your Rust test project

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        working-directory: libaries/tests/rust  # Specify the path to your Rust test project
        run: cargo check

  test_tests:
    name: Test Suite Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: libaries/tests/rust  # Specify the path to your Rust test project

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        working-directory: libaries/tests/rust  # Specify the path to your Rust test project
        run: cargo test

  lints_tests:
    name: Lints Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: libaries/tests/rust  # Specify the path to your Rust test project

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        working-directory: libaries/tests/rust  # Specify the path to your Rust test project
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        working-directory: libaries/tests/rust  # Specify the path to your Rust test project
        run: cargo clippy -- -D warnings
